# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AYL', '0003_commentmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentManager',
        ),
    ]
